#!/bin/bash
# Usage: iconlib -f /path/to/applist [-u] [-h]

# exit on error (we don't want this here)
# set -e

# check if fileicon is installed, otherwise change the PATH to use the provided version
if [[ ! -e `which fileicon` ]]; then
    export PATH=.:$PATH
fi

APPS="/Applications"
SEP=","
UNDO=""

WORK=`dirname pwd`
LOG=$WORK/log_`date "+%Y%m%d-%H%M%S"`.txt

HELP="iconlib
 usage: iconlib -f /path/to/applist [-u] [-h]
 
 mandatory argument:
   -f /path/to/applist   list of apps to be fixed

 optional arguments:
   -u                    undo icon fix
   -h                    show this help message and exit

"

# manage command line parameters
while getopts "f:uh" opt; do
    case $opt in
        f)  APPLIST="$OPTARG"
            ;;
        u)  UNDO=true
            ;;
        h)  echo "$HELP"
            exit 1
            ;;
        \?) echo "Invalid option -$OPTARG" >> $LOG 2>&1
            exit 1
            ;;
      esac

    case $APPLIST in
        -*) echo "Option $opt needs a valid argument"
            exit 1
            ;;
    esac
done


# start logging script output
echo `date` > $LOG


# check if the file containing the list of apps exists
if [[ ! -e "$APPLIST" ]]; then
    echo "App list file not found: $APPLIST"
    exit 1
fi

# read list of app to be processed and set/remove original .icns icon
while IFS=$SEP read name icon; do 

    app_name=$name.app
    ico_name=$(echo $icon | sed "s/^[ ]+|[ ]+$//")
    ico_path="$APPS/$app_name/Contents/Resources"


    # skip empty and commented out lines
    if [[ $name = "" || $name =~ ^# ]]; then
        continue
    fi
    
    # write name of application being processed
    echo "Application: " $app_name
    
    n_icons=$(ls -1 "$ico_path/"*".icns" | wc -l)
    test_name="$ico_path/$name.icns"
    
    # try to find icon to use
    #   case #1: there is only one icon in Contents/Resources folder
    if [[ $n_icons -eq 1 ]]; then
        ico_file=$(ls -1 "$ico_path/"*".icns")
        # echo "single icon: YES"
    
    #   case #2: icon name identical to app name
    elif [[ -e $test_name ]]; then
        ico_file="$test_name"
        # echo "identical: YES"
    
    #   case #3: if previous tests fail use icon name provided in app list
    elif [[ ! -e $test_name ]]; then
        ico_file="$ico_path/$ico_name"
    fi
    # end find icon
    
    echo "ico_file: " "$ico_file"
    echo ""
    
    
    if [[ ! $UNDO ]]; then
        fileicon set "$APPS/$app_name" "$ico_file" >> $LOG 2>&1
    else
        fileicon rm "$APPS/$app_name" >> $LOG 2>&1
    fi

done < $APPLIST
